### ISSUE TITLE
`pygw.file_utils.py` exception due to Python dictionary key.

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/global-workflow#1415]
**Detailed Description**

The `pygw.file_utils.py` throws the following error:

```

Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/scripts/exglobal_gfs_initialize.py", line 39, in <module>
    main()
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/scripts/exglobal_gfs_initialize.py", line 27, in main
    task.initialize()
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/ush/python/pygw/src/pygw/logger.py", line 261, in wrapper
    retval = func(*args, **kwargs)
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/ush/python/pygfs/ufswm/gfs.py", line 54, in initialize
    self.get_fixed_files()
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/ush/python/pygw/src/pygw/logger.py", line 261, in wrapper
    retval = func(*args, **kwargs)
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/ush/python/pygfs/ufswm/ufswm.py", line 163, in get_fixed_files
    FileHandler(fixed_data).sync()
  File "/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/ush/python/pygw/src/pygw/file_utils.py", line 39, in sync
    sync_factory[action](files)
KeyError: 'stage'
```

The corresponding YAML-formatted file which raises the exception can be found on RDHPCS Hera at `/scratch1/NCEPDEV/da/Henry.Winterbottom/UFS/global-workflow.dev/parm/ufs/forecast/ufs.atm.fixed_files.yaml`.

**Comment by aerorahul** [comment]
I think we identified the issue and resolved it.

**Comment by HenryRWinterbottom** [comment]
Yes, we did. Closing.
