### ISSUE TITLE
Issues on submitting executable jobs through python

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1579]
On hera at the directory `/scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/anl/`, I run the below command: 

```
srun '--export=ALL' -n 6 -A fv3-cpu /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe apply_incr.log
```
The run succeeded. 

However, when I tried to submit the above job through python, it failed. The python code for submitting the job is as below: 

```
        # execute apply_incr.exe to add incr to analysis
        exec_cmd = Executable(self.task_config.APRUN_LANDANL)
        exec_name = os.path.join(self.task_config.DATA, 'apply_incr.exe')
        exec_cmd.add_default_arg(exec_name)

        try:
            logger.debug(f"Executing {exec_cmd}")
            exec_cmd()
        except OSError:
            raise OSError(f"Failed to execute {exec_cmd}")
        except Exception:
            raise WorkflowException(f"An error occured during execution of {exec_cmd}")

        pass
```
The error message in the log file (/scratch1/NCEPDEV/global/Jiarui.Dong/ptmp/landid88/logs/2021032306/gdaslandanlfinal.log) is as below: 

```
^[[38;5;39m2023-05-04 18:06:46,726 - DEBUG    - land_analysis: Executing {} /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe^[[0m
^[[38;21m2023-05-04 18:06:46,738 - INFO     - root        : BEGIN: pygw.exceptions.__init__^[[0m
^[[38;5;39m2023-05-04 18:06:46,738 - DEBUG    - root        : ( WorkflowException('An error occured during execution of {} /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe'), 'An error occured during execution of {} /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe' )^[[0m
^[[38;5;196m2023-05-04 18:06:46,738 - ERROR    - root        : An error occured during execution of {} /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe^[[0m
^[[38;5;196m2023-05-04 18:06:46,738 - ERROR    - root        : An error occured during execution of {} /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe^[[0m
^[[38;21m2023-05-04 18:06:46,738 - INFO     - root        :   END: pygw.exceptions.__init__^[[0m
^[[38;5;39m2023-05-04 18:06:46,738 - DEBUG    - root        :  returning: None^[[0m
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python/pygw/src/pygw/executable.py", line 200, in __call__
    proc = subprocess.Popen(cmd, stdin=istream, stderr=estream, stdout=ostream, env=env, close_fds=False)
  File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '{}': '{}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python/pygfs/task/land_analysis.py", line 260, in _add_fms_cube_sphere_increments
    exec_cmd()
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python/pygw/src/pygw/executable.py", line 232, in __call__
    raise ProcessError(f"{self.exe[0]}: {e.strerror}", f"Command: {cmd_line_string}")
pygw.executable.ProcessError: {}: No such file or directory: '{}'
Command: '{}' '/scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid88/gdaslandanl_06/apply_incr.exe'
```
@aerorahul @CoryMartin-NOAA Do you have any suggestions? Thanks.

**Comment by aerorahul** [comment]
@jiaruidong2017 
The error message is quite clear.

**Comment by jiaruidong2017** [comment]
@aerorahul Do you mean `exec_cmd = Executable(self.task_config.APRUN_LANDANL)` is empty? Thanks.

**Comment by jiaruidong2017** [comment]
Thanks @aerorahul. The issue fixed and it worked now.
