### ISSUE TITLE
Run ioda converter in python

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1584]
I tried to run the ioda converter for generating the IMS data in the IODA format. The python code is as below: 

```
        # Execute imspy to create the IMS obs data in IODA format
        pdycyc = f"{to_YMD(self.task_config.PDY)}" + f"{self.task_config.cyc:02d}"
        ifile = 'IMSscf.' + f'{to_YMD(self.task_config.PDY)}' + '.' + f'{self.task_config.OROGTYPE}' + '.nc'
        ofile = f"{self.task_config.RUN}" + ".t" + f"{self.task_config.cyc:02d}" + "z.ims_snow_" + f"{pdycyc}" + ".nc4"

        # Reference the python script which does the actual work
        imspy = os.path.join(self.task_config.HOMEgfs, 'ush/imsfv3_scf2ioda.py')

        module_iconv = f"export PYTHONPATH={self.task_config.PYTHONPATH}:{self.task_config.HOMEgfs}/sorc/gdas.cd/iodaconv/src/:{self.task_config.HOMEgfs}/sorc/gdas.cd/build/lib/python3.7/pyioda/"
        print(f"module_iconv: {module_iconv}")
        os.system(module_iconv)
        cmd = f"python {imspy} -i {ifile} -o {ofile}"
        print(f"cmd: {cmd}")
        os.system(cmd)
```

The run failed and the error messages are below:

```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/imsfv3_scf2ioda.py", line 16, in <module>
    import lib_python.ioda_conv_engines as iconv
ModuleNotFoundError: No module named 'lib_python'
module_iconv: export PYTHONPATH=/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-3.0.0-intel-2021.5.0/install/intel/2021.5.0/py-pybind11-2.8.1-au5khm5/lib/python3.9/site-packages:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python/pygw/src:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/iodaconv/src/:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/build/lib/python3.7/pyioda/
cmd: python /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/imsfv3_scf2ioda.py -i IMSscf.20210323.C96_oro_data.nc -o gdas.t06z.ims_snow_2021032306.nc4
```

It seemed the issues resulting from the `lib_python`. @aerorahul @CoryMartin-NOAA do you have any suggestions? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 this is a `$PYTHONPATH` related issue but it looks like PYTHONPATH is set correctly... not sure what is going on here. My guess is `os.system` spawns a child that is independent of the parent? Why not add to the path from within python?

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA I don't know how to add the path with python, but I tried the following approach: 

```
        module_iconv = f"{self.task_config.HOMEgfs}/sorc/gdas.cd/iodaconv/src/:{self.task_config.HOMEgfs}/sorc/gdas.cd/build/lib/python3.7/pyioda/"
        print(f"module_iconv: {module_iconv}")
        sys.path.append(os.path.join(os.path.dirname(__file__), module_iconv))
        print(f"sys.path: {sys.path}")
        cmd = f"python {imspy} -i {ifile} -o {ofile}"
        print(f"cmd: {cmd}")
        os.system(cmd)
```

It produced the same errors as below:

```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/imsfv3_scf2ioda.py", line 16, in <module>
    import lib_python.ioda_conv_engines as iconv
ModuleNotFoundError: No module named 'lib_python'
module_iconv: /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/iodaconv/src/:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/build/lib/python3.7/pyioda/
sys.path: ['/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/scripts', '/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-3.0.0-intel-2021.5.0/install/intel/2021.5.0/py-pybind11-2.8.1-au5khm5/lib/python3.9/site-packages', '/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python', '/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/python/pygw/src', '/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python37.zip', '/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7', '/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/lib-dynload', '/home/Jiarui.Dong/.local/lib/python3.7/site-packages', '/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/task/src/fv3-jedi-tools/src', '/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/lib/python3.7/site-packages', '/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/iodaconv/src/:/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/sorc/gdas.cd/build/lib/python3.7/pyioda/']
cmd: python /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid88/ush/imsfv3_scf2ioda.py -i IMSscf.20210323.C96_oro_data.nc -o gdas.t06z.ims_snow_2021032306.nc4
```

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 if sys.path.append didn't work then the issue is probably still related to child/parent processes.

**Comment by aerorahul** [comment]
We should not do this funky business inside of a python script.
Why can't we do this in `landanlrun.sh` or whatever the rocoto job script this is needed in?

**Comment by jiaruidong2017** [comment]
> We should not do this funky business inside of a python script. Why can't we do this in `landanlrun.sh` or whatever the rocoto job script this is needed in?

@aerorahul It is part of the IMS data processing. If you agree, I can move this part to the landanlrun.sh. Thanks.

**Comment by CoryMartin-NOAA** [comment]
Just to clarify @jiaruidong2017, @aerorahul wants the PYTHONPATH, etc. stuff put in the rocoto script, but keep the execution in the ex-script.

**Comment by aerorahul** [comment]
If this is data processing, we agreed to put this in `landanlprep.sh`, no?
`landanlrun.sh`  should be creating the ensemble backgrounds for the EnOI and run the JEDI ENOI executable.
Or have we since diverged?

**Comment by jiaruidong2017** [comment]
Thanks @CoryMartin-NOAA for clarifying it.

**Comment by CoryMartin-NOAA** [comment]
yes this is I think `prep` based on what I can see

**Comment by jiaruidong2017** [comment]
@aerorahul @CoryMartin-NOAA Okay, I will try to work on this in the `landanlprep.sh` and let you know then. Thanks.

**Comment by jiaruidong2017** [comment]
I added the lib path (`gdasappPATH`) in the landanlprep.sh as below:

```
# setup python path for workflow utilities and tasks
pygwPATH="${HOMEgfs}/ush/python:${HOMEgfs}/ush/python/pygw/src"
gdasappPATH="${HOMEgfs}/sorc/gdas.cd/iodaconv/src/:${HOMEgfs}/sorc/gdas.cd/build/lib/python3.7/pyioda/"
PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${pygwPATH}:${gdasappPATH}"
export PYTHONPATH
```

It worked and successfully generated the IMS data in IODA format. Please let me know if the above implementation need some changes. Thanks.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA @aerorahul I just run the global-workflow, and met the similar issue `ModuleNotFoundError: No module named 'pyioda'` and detailed error messages are as below:

```
0:  writing output to ./IMSscf.20210323.C96_oro_data.nc
0:  writing out       11199  observations
^[[38;21m2023-07-09 21:15:34,470 - INFO     - land_analysis: Create IMS obs data in IODA format^[[0m
^[[38;5;39m2023-07-09 21:15:34,470 - DEBUG    - land_analysis: Executing /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py -i /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/IMSscf.20210323.C96_oro_data.nc -o /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/ims_snow_2021032318.nc4^[[0m
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py", line 16, in <module>
    import pyiodaconv.ioda_conv_engines as iconv
  File "/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/sorc/gdas.cd/iodaconv/src/pyiodaconv/ioda_conv_engines.py", line 3, in <module>
    from pyioda import ioda_obs_space as ioda_os
ModuleNotFoundError: No module named 'pyioda'
^[[38;21m2023-07-09 21:15:34,770 - INFO     - root        : BEGIN: pygw.exceptions.__init__^[[0m
^[[38;5;39m2023-07-09 21:15:34,770 - DEBUG    - root        : ( WorkflowException('An error occured during execution of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py -i /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/IMSscf.20210323.C96_oro_data.nc -o /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/ims_snow_2021032318.nc4'), 'An error occured during execution of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py -i /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/IMSscf.20210323.C96_oro_data.nc -o /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/ims_snow_2021032318.nc4' )^[[0m
^[[38;5;196m2023-07-09 21:15:34,770 - ERROR    - root        : An error occured during execution of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py -i /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/IMSscf.20210323.C96_oro_data.nc -o /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/ims_snow_2021032318.nc4^[[0m
^[[38;5;196m2023-07-09 21:15:34,770 - ERROR    - root        : An error occured during execution of /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/ush/imsfv3_scf2ioda.py -i /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/IMSscf.20210323.C96_oro_data.nc -o /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/preplandobs.195908/ims_snow_2021032318.nc4^[[0m
^[[38;21m2023-07-09 21:15:34,771 - INFO     - root        :   END: pygw.exceptions.__init__^[[0m
^[[38;5;39m2023-07-09 21:15:34,771 - DEBUG    - root        :  returning: None^[[0m
```
Is there any change in handling modules I may ignore? Thanks.

**Comment by CoryMartin-NOAA** [comment]
It's not a module issue @jiaruidong2017 it's a pythonpath issue. Remove `/pyioda` from the end of your pythonpath

**Comment by jiaruidong2017** [comment]
Thanks @CoryMartin-NOAA It works.
