### ISSUE TITLE
RTD build pipeline is broken

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1595]
**Expected behavior**
Documentation should automatically be built and posted on Read-the-Docs when develop is updated.

**Current behavior**
The RTD build fails with the following error:
```
Running Sphinx v5.3.0

<traceback omitted>
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168

The above exception was the direct cause of the following exception:

<traceback omitted>

sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)

Extension error:
Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
```

**Machines affected**
NA

**To Reproduce**
Merge and PR to develop and view [build status on RTD](https://readthedocs.org/projects/global-workflow/builds/)

**Context**
This seems to a direct result of a change to the RTD defaults due to a library in conflict with the docker image: https://github.com/readthedocs/readthedocs.org/issues/10290

**Detailed Description**

**Additional Information**

**Possible Implementation**
Add a .readthedoc.yaml file to specify the Ubuntu version to use

**Comment by WalterKolczynski-NOAA** [comment]
Still failing after attempted fix

**Comment by WalterKolczynski-NOAA** [comment]
Still failing, but now with a different error:
```
Running Sphinx v6.2.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sphinxcontrib.bibtex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 229, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 404, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/global-workflow/envs/latest/lib/python3.11/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib.bibtex')
```

**Comment by WalterKolczynski-NOAA** [comment]
Still no luck.

**Comment by WalterKolczynski-NOAA** [comment]
Finally fixed after much struggle.
