### ISSUE TITLE
The model does not compile on orion in the develop branch (1/16) 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2224]
### What is wrong?

The ufs model does not compile on orion in the develop branch.  

Checked out fresh clone of g-w, updated submodules, and build, and get the following errors in /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/logs/build_ufs.log
```
-- Found Python: /apps/intel-2022.1.2/intel-2022.1.2/intelpython/latest/bin/python3.9 (found suitable version "3.9.7", minimum required is "3.6") found components: Interpreter
Found Python: /apps/intel-2022.1.2/intel-2022.1.2/intelpython/latest/bin/python3.9
-- Compile stochastic_physics with 64-bit precision to match CCPP slow physics.
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_GFS_v17_p8_ugwpv1,FV3_GFS_v17_coupled_p8_ugwpv1 ...
CMake Error at FV3/ccpp/CMakeLists.txt:40 (message):
  An error occured while running ccpp_prebuild.py, check
  /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/build_fv3_0/FV3/ccpp/ccpp_prebuild.{out,err}


-- Configuring incomplete, errors occurred!
See also "/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/build_fv3_0/CMakeFiles/CMakeOutput.log".
```
from   /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/build_fv3_0/FV3/ccpp/ccpp_prebuild.err: 

```
Parsing scheme GFS_rrtmgp_post_run, at GFS_rrtmgp_post.meta:9
INFO: Parsing scheme GFS_rrtmgp_post_run, at GFS_rrtmgp_post.meta:9
INFO: Parsed tables in scheme GFS_rrtmgp_post with dependencies ['../../Radiation/RRTMG/radlw_param.f', '../../Radiation/RRTMGP/rte-rrtmgp/extensions/mo_heating_rates.F90', '../../Radiation/radiation_aerosols.f', '../../Radiation/radiation_tools.F90', '../../hooks/machine.F']
Traceback (most recent call last):
  File "/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 813, in <module>
    main()
  File "/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 736, in main
    (success, metadata_request, arguments_request, dependencies_request, schemes_in_files) = collect_physics_subroutines(config['scheme_files'])
  File "/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 328, in collect_physics_subroutines
    (metadata, arguments, dependencies) = parse_scheme_tables(scheme_filepath, scheme_filename)
  File "/work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/ccpp/framework/scripts/metadata_parser.py", line 766, in parse_scheme_tables
    raise Exception("Dependency {} for scheme table {} does not exit".format(dependency, scheme_name))
Exception: Dependency /work2/noaa/marine/jmeixner/HR3/develop/global-workflow/sorc/ufs_model.fd/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/../../Radiation/RRTMGP/rte-rrtmgp/extensions/mo_heating_rates.F90 for scheme table GFS_rrtmgp_post does not exit
```

### What should have happened?

I should be able to compile components of the g-w in the develop branch. 

### What machines are impacted?

Orion

### Steps to reproduce

Clone develop on orion and try to build... 

### Additional information

Will start trying on hera and report if it's broken there too. 

### Do you have a proposed solution?

n/a

**Comment by JessicaMeixner-NOAA** [comment]
The issue might have actually been in the submoule recursive clone.  I've looked back and found: 
`Failed to recurse into submodule path 'sorc/ufs_model.fd'. `

I've updated my git version by loading the git module and and am trying again in a fresh clone.

**Comment by JessicaMeixner-NOAA** [comment]
Turns out this is an issue with git.
